import Head from "next/head";
import Banner from "../components/Banner";
import Header from "../components/Header";
import ProductFeed from "../components/ProductFeed";

export default function Home({ products }) {

  return (
    <div>
      <Head>
        <title>Amazon 2.0 With Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      {/* Header */}
      <Header />

      <main className="max-w-screen-2xl mx-auto bg-gray-100">
        {/* Banner */}
        <Banner />

        {/* Product */}
        <ProductFeed products={products} />
      </main>
    </div>
  );
}

export async function getServerSideProps(context) {
  const data = await fetch("https://fakestoreapi.com/products")
  const products = await data.json()

  return {
    props: {
      products,
    },
  };
}
